"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-28 09:19:37.209639

Also installs row-level security, composite same-owner foreign keys,
immutability triggers for version tables, and least-privilege grants
for the runtime role (APP_DB_ROLE).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from fitcoach.config import get_settings

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_global_budget",
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("calls", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("day"),
    )
    op.create_table(
        "processed_updates",
        sa.Column("update_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("update_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("language", sa.String(length=5), server_default="ru", nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("units", sa.String(length=10), nullable=True),
        sa.Column(
            "onboarding_step", sa.String(length=20), server_default="language", nullable=False
        ),
        sa.Column("age_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_text_consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("goal", sa.String(length=20), nullable=True),
        sa.Column("daily_kcal_target", sa.Numeric(precision=7, scale=1), nullable=True),
        sa.Column("target_set_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_table(
        "activity_types",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_types_owner_id"), "activity_types", ["owner_id"], unique=False
    )
    op.create_table(
        "ai_calls",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("task", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_calls_owner_id"), "ai_calls", ["owner_id"], unique=False)
    op.create_table(
        "ai_user_budget",
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("calls", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("owner_id", "day"),
    )
    op.create_table(
        "drafts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drafts_owner_id"), "drafts", ["owner_id"], unique=False)
    op.create_table(
        "weight_entries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("weight_kg", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weight_entries_owner_id"), "weight_entries", ["owner_id"], unique=False
    )
    op.create_table(
        "activity_type_versions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("activity_type_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["activity_type_id"], ["activity_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activity_type_id", "version"),
    )
    op.create_index(
        op.f("ix_activity_type_versions_owner_id"),
        "activity_type_versions",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "food_entries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("eaten_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("energy_kcal", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("protein_g", sa.Numeric(precision=7, scale=1), nullable=True),
        sa.Column("fat_g", sa.Numeric(precision=7, scale=1), nullable=True),
        sa.Column("carbs_g", sa.Numeric(precision=7, scale=1), nullable=True),
        sa.Column("precision", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=16), server_default="manual", nullable=False),
        sa.Column("draft_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["draft_id"], ["drafts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_food_entries_owner_id"), "food_entries", ["owner_id"], unique=False)
    op.create_table(
        "workout_templates",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("activity_type_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["activity_type_id"], ["activity_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workout_templates_owner_id"), "workout_templates", ["owner_id"], unique=False
    )
    op.create_table(
        "workout_template_versions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("template_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("activity_type_version_id", sa.BigInteger(), nullable=False),
        sa.Column("targets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_type_version_id"], ["activity_type_versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["template_id"], ["workout_templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("template_id", "version"),
    )
    op.create_index(
        op.f("ix_workout_template_versions_owner_id"),
        "workout_template_versions",
        ["owner_id"],
        unique=False,
    )
    op.create_table(
        "workout_sessions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("activity_type_version_id", sa.BigInteger(), nullable=False),
        sa.Column("template_version_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="completed", nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activity_name", sa.String(length=60), nullable=False),
        sa.Column("template_name", sa.String(length=60), nullable=True),
        sa.Column("field_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_values", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_type_version_id"], ["activity_type_versions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["template_version_id"], ["workout_template_versions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workout_sessions_owner_id"), "workout_sessions", ["owner_id"], unique=False
    )
    op.create_table(
        "planned_workouts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("template_version_id", sa.BigInteger(), nullable=False),
        sa.Column("planned_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="planned", nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["workout_sessions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["template_version_id"], ["workout_template_versions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_planned_workouts_owner_id"), "planned_workouts", ["owner_id"], unique=False
    )
    # ### end Alembic commands ###
    _security_upgrade()


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS fc_forbid_update() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS app_current_user_id() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS app_current_telegram_id() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_planned_workouts_owner_id"), table_name="planned_workouts")
    op.drop_table("planned_workouts")
    op.drop_index(op.f("ix_workout_sessions_owner_id"), table_name="workout_sessions")
    op.drop_table("workout_sessions")
    op.drop_index(
        op.f("ix_workout_template_versions_owner_id"), table_name="workout_template_versions"
    )
    op.drop_table("workout_template_versions")
    op.drop_index(op.f("ix_workout_templates_owner_id"), table_name="workout_templates")
    op.drop_table("workout_templates")
    op.drop_index(op.f("ix_food_entries_owner_id"), table_name="food_entries")
    op.drop_table("food_entries")
    op.drop_index(op.f("ix_activity_type_versions_owner_id"), table_name="activity_type_versions")
    op.drop_table("activity_type_versions")
    op.drop_index(op.f("ix_weight_entries_owner_id"), table_name="weight_entries")
    op.drop_table("weight_entries")
    op.drop_index(op.f("ix_drafts_owner_id"), table_name="drafts")
    op.drop_table("drafts")
    op.drop_table("ai_user_budget")
    op.drop_index(op.f("ix_ai_calls_owner_id"), table_name="ai_calls")
    op.drop_table("ai_calls")
    op.drop_index(op.f("ix_activity_types_owner_id"), table_name="activity_types")
    op.drop_table("activity_types")
    op.drop_table("users")
    op.drop_table("processed_updates")
    op.drop_table("ai_global_budget")
    # ### end Alembic commands ###


OWNED_TABLES = (
    "food_entries",
    "weight_entries",
    "activity_types",
    "activity_type_versions",
    "workout_templates",
    "workout_template_versions",
    "planned_workouts",
    "workout_sessions",
    "drafts",
    "ai_user_budget",
    "ai_calls",
)
IMMUTABLE_TABLES = ("activity_type_versions", "workout_template_versions")
# child table, child column, parent table, on-delete action
SAME_OWNER_FKS = (
    ("activity_type_versions", "activity_type_id", "activity_types", "CASCADE"),
    ("workout_templates", "activity_type_id", "activity_types", "CASCADE"),
    ("workout_template_versions", "template_id", "workout_templates", "CASCADE"),
    ("workout_template_versions", "activity_type_version_id", "activity_type_versions", "CASCADE"),
    ("planned_workouts", "template_version_id", "workout_template_versions", "CASCADE"),
    ("planned_workouts", "session_id", "workout_sessions", "SET NULL (session_id)"),
    ("workout_sessions", "activity_type_version_id", "activity_type_versions", "CASCADE"),
    (
        "workout_sessions",
        "template_version_id",
        "workout_template_versions",
        "SET NULL (template_version_id)",
    ),
    ("food_entries", "draft_id", "drafts", "SET NULL (draft_id)"),
)
CHECKS = (
    ("food_entries", "precision IN ('measured', 'approximate', 'unknown')"),
    ("food_entries", "source IN ('manual', 'ai_draft')"),
    ("food_entries", "energy_kcal IS NULL OR energy_kcal >= 0"),
    ("weight_entries", "weight_kg > 0"),
    ("planned_workouts", "status IN ('planned', 'completed', 'skipped', 'cancelled')"),
    ("workout_sessions", "status IN ('completed')"),
    ("drafts", "status IN ('pending', 'confirmed', 'cancelled')"),
    (
        "users",
        "onboarding_step IN ('language', 'age', 'privacy', 'timezone', 'units', "
        "'goal', 'target', 'done')",
    ),
    ("users", "language IN ('ru', 'en')"),
)


def _security_upgrade() -> None:
    role = get_settings().app_db_role
    if not role.replace("_", "").isalnum():
        raise ValueError("invalid APP_DB_ROLE")

    op.execute(
        """
        CREATE FUNCTION app_current_user_id() RETURNS bigint LANGUAGE sql STABLE AS
        $$ SELECT nullif(current_setting('app.user_id', true), '')::bigint $$
        """
    )
    op.execute(
        """
        CREATE FUNCTION app_current_telegram_id() RETURNS bigint LANGUAGE sql STABLE AS
        $$ SELECT nullif(current_setting('app.telegram_id', true), '')::bigint $$
        """
    )
    op.execute(
        """
        CREATE FUNCTION fc_forbid_update() RETURNS trigger LANGUAGE plpgsql AS
        $$ BEGIN RAISE EXCEPTION '% rows are immutable', TG_TABLE_NAME; END $$
        """
    )

    for table, expr in CHECKS:
        op.execute(f"ALTER TABLE {table} ADD CHECK ({expr})")

    parents = sorted({parent for _, _, parent, _ in SAME_OWNER_FKS})
    for parent in parents:
        op.execute(
            f"ALTER TABLE {parent} ADD CONSTRAINT uq_{parent}_id_owner UNIQUE (id, owner_id)"
        )
    for child, column, parent, action in SAME_OWNER_FKS:
        op.execute(
            f"ALTER TABLE {child} ADD CONSTRAINT fk_{child}_{column}_same_owner "
            f"FOREIGN KEY ({column}, owner_id) REFERENCES {parent} (id, owner_id) "
            f"ON DELETE {action}"
        )

    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY users_self ON users "
        "USING (telegram_id = app_current_telegram_id()) "
        "WITH CHECK (telegram_id = app_current_telegram_id())"
    )
    for table in OWNED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY owner_isolation ON {table} "
            "USING (owner_id = app_current_user_id()) "
            "WITH CHECK (owner_id = app_current_user_id())"
        )
    for table in IMMUTABLE_TABLES:
        op.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION fc_forbid_update()"
        )

    op.execute(f"GRANT USAGE ON SCHEMA public TO {role}")
    op.execute(
        f"GRANT EXECUTE ON FUNCTION app_current_user_id(), app_current_telegram_id() TO {role}"
    )
    for table in ("users", *OWNED_TABLES):
        privileges = (
            "SELECT, INSERT" if table in IMMUTABLE_TABLES else "SELECT, INSERT, UPDATE, DELETE"
        )
        op.execute(f"GRANT {privileges} ON {table} TO {role}")
    op.execute(f"GRANT SELECT, INSERT, DELETE ON processed_updates TO {role}")
    op.execute(f"GRANT SELECT, INSERT, UPDATE ON ai_global_budget TO {role}")
    op.execute(f"GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {role}")
