"""p1 nutrition training reminders

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29 00:45:04.303829
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from fitcoach.config import get_settings

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "foods",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("brand", sa.String(length=80), nullable=True),
        sa.Column("basis", sa.String(length=8), nullable=False),
        sa.Column("serving_g", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("energy_kcal", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("protein_g", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("fat_g", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("carbs_g", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("fiber_g", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("preparation", sa.String(length=16), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=True),
        sa.Column("source_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("favorite", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_foods_owner_id"), "foods", ["owner_id"], unique=False)
    op.create_table(
        "import_batches",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "kind", "file_sha256"),
    )
    op.create_index(
        op.f("ix_import_batches_owner_id"), "import_batches", ["owner_id"], unique=False
    )
    op.create_table(
        "programs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_programs_owner_id"), "programs", ["owner_id"], unique=False)
    op.create_table(
        "reminders",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("text", sa.String(length=200), nullable=True),
        sa.Column("local_time", sa.Time(), nullable=False),
        sa.Column("days_mask", sa.SmallInteger(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("next_fire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reminders_owner_id"), "reminders", ["owner_id"], unique=False)
    op.create_table(
        "saved_meals",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("cooked_yield_g", sa.Numeric(precision=8, scale=1), nullable=True),
        sa.Column("servings", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("favorite", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("items", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_saved_meals_owner_id"), "saved_meals", ["owner_id"], unique=False)
    op.create_table(
        "reminder_deliveries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("reminder_id", sa.BigInteger(), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("error", sa.String(length=40), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reminder_id"], ["reminders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reminder_id", "scheduled_for"),
    )
    op.create_index(
        op.f("ix_reminder_deliveries_owner_id"), "reminder_deliveries", ["owner_id"], unique=False
    )
    op.add_column(
        "activity_types",
        sa.Column("kind", sa.String(length=16), server_default="custom", nullable=False),
    )
    op.add_column(
        "activity_types",
        sa.Column("counts_as_training", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column(
        "ai_calls", sa.Column("media", sa.String(length=8), server_default="none", nullable=False)
    )
    op.add_column("ai_calls", sa.Column("latency_ms", sa.Integer(), nullable=True))
    op.add_column(
        "ai_calls", sa.Column("refunded", sa.Boolean(), server_default="false", nullable=False)
    )
    op.add_column(
        "ai_user_budget", sa.Column("media_calls", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("drafts", sa.Column("version", sa.Integer(), server_default="1", nullable=False))
    op.add_column(
        "food_entries", sa.Column("fiber_g", sa.Numeric(precision=7, scale=1), nullable=True)
    )
    op.add_column("food_entries", sa.Column("meal_type", sa.String(length=12), nullable=True))
    op.add_column(
        "food_entries", sa.Column("amount", sa.Numeric(precision=9, scale=2), nullable=True)
    )
    op.add_column("food_entries", sa.Column("unit", sa.String(length=12), nullable=True))
    op.add_column(
        "food_entries", sa.Column("grams", sa.Numeric(precision=8, scale=1), nullable=True)
    )
    op.add_column("food_entries", sa.Column("nutrient_source", sa.String(length=16), nullable=True))
    op.add_column("food_entries", sa.Column("food_id", sa.BigInteger(), nullable=True))
    op.add_column(
        "users", sa.Column("protein_target_g", sa.Numeric(precision=6, scale=1), nullable=True)
    )
    op.add_column(
        "users", sa.Column("fat_target_g", sa.Numeric(precision=6, scale=1), nullable=True)
    )
    op.add_column(
        "users", sa.Column("carbs_target_g", sa.Numeric(precision=6, scale=1), nullable=True)
    )
    op.add_column(
        "users", sa.Column("ai_media_consent_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("users", sa.Column("quiet_start", sa.Time(), nullable=True))
    op.add_column("users", sa.Column("quiet_end", sa.Time(), nullable=True))
    op.add_column(
        "workout_sessions",
        sa.Column(
            "blocks", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
    )
    op.add_column(
        "workout_sessions",
        sa.Column("source", sa.String(length=16), server_default="manual", nullable=False),
    )
    op.add_column("workout_sessions", sa.Column("source_ref", sa.String(length=80), nullable=True))
    op.add_column("workout_sessions", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column(
        "workout_template_versions",
        sa.Column(
            "blocks", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
    )
    op.add_column("workout_templates", sa.Column("program_id", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###
    _security_upgrade()


def downgrade() -> None:
    op.execute("DROP FUNCTION IF EXISTS app_due_reminders(timestamptz, integer)")
    op.execute("DROP INDEX IF EXISTS uq_workout_sessions_source_ref")
    for table, name, _expr in reversed(NEW_CHECKS):
        op.execute(f"ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {name}")
    op.execute("ALTER TABLE food_entries DROP CONSTRAINT IF EXISTS food_entries_precision_check")
    op.execute("ALTER TABLE food_entries DROP CONSTRAINT IF EXISTS food_entries_source_check")
    for child, column, _parent, _action in reversed(SAME_OWNER_FKS):
        op.execute(f"ALTER TABLE {child} DROP CONSTRAINT IF EXISTS fk_{child}_{column}_same_owner")
    for parent in NEW_PARENTS:
        op.execute(f"ALTER TABLE {parent} DROP CONSTRAINT IF EXISTS uq_{parent}_id_owner")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workout_templates", "program_id")
    op.drop_column("workout_template_versions", "blocks")
    op.drop_column("workout_sessions", "notes")
    op.drop_column("workout_sessions", "source_ref")
    op.drop_column("workout_sessions", "source")
    op.drop_column("workout_sessions", "blocks")
    op.drop_column("users", "quiet_end")
    op.drop_column("users", "quiet_start")
    op.drop_column("users", "ai_media_consent_at")
    op.drop_column("users", "carbs_target_g")
    op.drop_column("users", "fat_target_g")
    op.drop_column("users", "protein_target_g")
    op.drop_column("food_entries", "food_id")
    op.drop_column("food_entries", "nutrient_source")
    op.drop_column("food_entries", "grams")
    op.drop_column("food_entries", "unit")
    op.drop_column("food_entries", "amount")
    op.drop_column("food_entries", "meal_type")
    op.drop_column("food_entries", "fiber_g")
    op.drop_column("drafts", "version")
    op.drop_column("ai_user_budget", "media_calls")
    op.drop_column("ai_calls", "refunded")
    op.drop_column("ai_calls", "latency_ms")
    op.drop_column("ai_calls", "media")
    op.drop_column("activity_types", "counts_as_training")
    op.drop_column("activity_types", "kind")
    op.drop_index(op.f("ix_reminder_deliveries_owner_id"), table_name="reminder_deliveries")
    op.drop_table("reminder_deliveries")
    op.drop_index(op.f("ix_saved_meals_owner_id"), table_name="saved_meals")
    op.drop_table("saved_meals")
    op.drop_index(op.f("ix_reminders_owner_id"), table_name="reminders")
    op.drop_table("reminders")
    op.drop_index(op.f("ix_programs_owner_id"), table_name="programs")
    op.drop_table("programs")
    op.drop_index(op.f("ix_import_batches_owner_id"), table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index(op.f("ix_foods_owner_id"), table_name="foods")
    op.drop_table("foods")
    # ### end Alembic commands ###
    op.execute(
        "ALTER TABLE food_entries ADD CONSTRAINT food_entries_precision_check "
        "CHECK (precision IN ('measured', 'approximate', 'unknown'))"
    )
    op.execute(
        "ALTER TABLE food_entries ADD CONSTRAINT food_entries_source_check "
        "CHECK (source IN ('manual', 'ai_draft'))"
    )


NEW_TABLES = (
    "foods",
    "saved_meals",
    "programs",
    "import_batches",
    "reminders",
    "reminder_deliveries",
)
NEW_PARENTS = ("foods", "programs", "reminders")
SAME_OWNER_FKS = (
    ("food_entries", "food_id", "foods", "SET NULL (food_id)"),
    ("workout_templates", "program_id", "programs", "SET NULL (program_id)"),
    ("reminder_deliveries", "reminder_id", "reminders", "CASCADE"),
)
NEW_CHECKS = (
    (
        "food_entries",
        "food_entries_meal_type_check",
        "meal_type IS NULL OR meal_type IN ('breakfast', 'lunch', 'dinner', 'snack')",
    ),
    ("food_entries", "food_entries_grams_check", "grams IS NULL OR grams >= 0"),
    ("foods", "foods_basis_check", "basis IN ('100g', '100ml', 'serving')"),
    ("foods", "foods_source_check", "source IN ('user', 'label', 'usda', 'off', 'recipe')"),
    ("foods", "foods_kcal_check", "energy_kcal IS NULL OR energy_kcal >= 0"),
    ("saved_meals", "saved_meals_kind_check", "kind IN ('meal', 'recipe')"),
    (
        "activity_types",
        "activity_types_kind_check",
        "kind IN ('custom', 'strength', 'swimming', 'enduro', 'moto_ride')",
    ),
    ("import_batches", "import_batches_status_check", "status IN ('preview', 'imported')"),
    ("reminders", "reminders_kind_check", "kind IN ('weigh_in', 'workout', 'meals', 'custom')"),
    ("reminders", "reminders_days_check", "days_mask BETWEEN 1 AND 127"),
    (
        "reminder_deliveries",
        "reminder_deliveries_status_check",
        "status IN ('sending', 'sent', 'failed', 'blocked', 'skipped')",
    ),
)


def _security_upgrade() -> None:
    role = get_settings().app_db_role
    if not role.replace("_", "").isalnum():
        raise ValueError("invalid APP_DB_ROLE")

    op.execute("ALTER TABLE food_entries DROP CONSTRAINT food_entries_precision_check")
    op.execute(
        "ALTER TABLE food_entries ADD CONSTRAINT food_entries_precision_check "
        "CHECK (precision IN ('measured', 'recipe', 'approximate', 'unknown'))"
    )
    op.execute("ALTER TABLE food_entries DROP CONSTRAINT food_entries_source_check")
    op.execute(
        "ALTER TABLE food_entries ADD CONSTRAINT food_entries_source_check "
        "CHECK (source IN ('manual', 'ai_draft', 'copy', 'saved', 'text'))"
    )
    for table, name, expr in NEW_CHECKS:
        op.execute(f"ALTER TABLE {table} ADD CONSTRAINT {name} CHECK ({expr})")

    for parent in NEW_PARENTS:
        op.execute(
            f"ALTER TABLE {parent} ADD CONSTRAINT uq_{parent}_id_owner UNIQUE (id, owner_id)"
        )
    for child, column, parent, action in SAME_OWNER_FKS:
        op.execute(
            f"ALTER TABLE {child} ADD CONSTRAINT fk_{child}_{column}_same_owner "
            f"FOREIGN KEY ({column}, owner_id) REFERENCES {parent} (id, owner_id) "
            f"ON DELETE {action}"
        )
    op.execute(
        "CREATE UNIQUE INDEX uq_workout_sessions_source_ref ON workout_sessions "
        "(owner_id, source_ref) WHERE source_ref IS NOT NULL"
    )

    for table in NEW_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY owner_isolation ON {table} "
            "USING (owner_id = app_current_user_id()) "
            "WITH CHECK (owner_id = app_current_user_id())"
        )
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO {role}")
    op.execute(f"GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO {role}")

    # The reminder scheduler needs to find due reminders across users. This narrow
    # SECURITY DEFINER function returns only ids needed to bind each user's own
    # RLS context; it exposes no diary or health data.
    op.execute(
        """
        CREATE FUNCTION app_due_reminders(p_now timestamptz, p_limit integer)
        RETURNS TABLE (reminder_id bigint, owner_id bigint, telegram_id bigint)
        LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public, pg_temp AS $$
            SELECT r.id, r.owner_id, u.telegram_id
            FROM reminders r JOIN users u ON u.id = r.owner_id
            WHERE r.enabled AND r.next_fire_at IS NOT NULL AND r.next_fire_at <= p_now
            ORDER BY r.next_fire_at
            LIMIT least(greatest(p_limit, 0), 500)
        $$
        """
    )
    op.execute("REVOKE ALL ON FUNCTION app_due_reminders(timestamptz, integer) FROM PUBLIC")
    op.execute(f"GRANT EXECUTE ON FUNCTION app_due_reminders(timestamptz, integer) TO {role}")
